kitSocketHost = '***'
kitSocketPort = 15485
kitMQHost = '***'
kitMQPort = 5672
kitMQUsername = '***'
kitMQPassword = '***'
kitMQQueueName = '***'
kitMQHeartBeat = None
# kitMQHeartBeat = 0
kitDBHost = '***'
kitDBPort = 3306
kitDBUsername = '***'
kitDBPassword = '***'
kitDBName = '***'
